import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';
import * as cors from 'cors';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe({ 
    transform: true, 
    whitelist: true, 
    forbidNonWhitelisted: true,
  }));

  app.use(cors({
    origin: "*",
    credentials: true,
  }));

  await app.listen(7000, "0.0.0.0");
}
bootstrap();




[
  {
      "id": 8,
      "sku": "ABCDE123",
      "name": "Рычаг подвески",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 1,
      "shortDescription": "Рычаг подвески для автомобиля",
      "description": "Это высококачественный рычаг подвески для вашего автомобиля, разработанный для долговечности и производительности.",
      "inStock": true,
      "images": [],
      "carName": "Toyota Corolla",
      "model": "2020",
      "oem": "OEM1234",
      "years": "2015-2020",
      "price": 100,
      "imageUrl": "https://www.shutterstock.com/image-illustration/car-parts-auto-spare-isolated-600nw-2283939101.jpg",
      "trtCode": "12345667",
      "brand": "Toyota",
      "categories": []
  },
  {
      "id": 9,
      "sku": "ABCDE122",
      "name": "Рычаг подвески",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 1,
      "shortDescription": "Рычаг подвески для автомобиля",
      "description": "Это высококачественный рычаг подвески для вашего автомобиля, разработанный для долговечности и производительности.",
      "inStock": true,
      "images": [],
      "carName": "Toyota Corolla",
      "model": "2020",
      "oem": "OEM1234",
      "years": "2015-2020",
      "price": 100,
      "imageUrl": "https://www.shutterstock.com/image-photo/various-car-parts-260nw-517813702.jpg",
      "trtCode": "12345667",
      "brand": "Toyota",
      "categories": []
  },
  {
      "id": 10,
      "sku": "XYZ98765",
      "name": "Тормозной диск",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для автомобиля",
      "description": "Этот высококачественный тормозной диск обеспечит отличное торможение и долгий срок службы, даже в самых сложных условиях эксплуатации.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://media.istockphoto.com/id/1034249292/photo/set-of-car-parts-isolated-on-white-background-3d.jpg?s=612x612&w=0&k=20&c=BwXl3LzQau4v40nl9INYToE0mC1SYDA4gBkylspbYis=",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 11,
      "sku": "XYZ98764",
      "name": "Тормозной диск",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для автомобиля",
      "description": "Этот высококачественный тормозной диск обеспечит отличное торможение и долгий срок службы, даже в самых сложных условиях эксплуатации.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://turnkey-sourcing.de/uploads/beispiele-automobilindustrie_.webp",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 12,
      "sku": "XYZ98744",
      "name": "Тормозной диск",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для автомобиля",
      "description": "Этот высококачественный тормозной диск обеспечит отличное торможение и долгий срок службы, даже в самых сложных условиях эксплуатации.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPwcFxw9thYsEsY0jn981k1eIaMx4-1RmOtQ&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 13,
      "sku": "XYZ98467",
      "name": "Тормозной диск",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для автомобиля",
      "description": "Этот высококачественный тормозной диск обеспечит отличное торможение и долгий срок службы, даже в самых сложных условиях эксплуатации.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiCXLN_yVc2ER8xvmRXTjbQIvbhWk50Q30jg&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 14,
      "sku": "FDG98467",
      "name": "Диск тормозной для автомобилей Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Диск тормозной для автомобиля Honda Civic",
      "description": "Этот высококачественный тормозной диск обеспечит превосходную эффективность торможения и долговечность, выдерживая любые условия эксплуатации, от жарких летних температур до экстремальных зимних холодов.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7yTQUTQeDXtgzdGWAZg5k-0pdhI4by95hIQ&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 15,
      "sku": "HJG88467",
      "name": "Диск тормозной для автомобилей Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Диск тормозной для автомобиля Honda Civic",
      "description": "Этот высококачественный тормозной диск обеспечит превосходную эффективность торможения и долговечность, выдерживая любые условия эксплуатации, от жарких летних температур до экстремальных зимних холодов.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://media.istockphoto.com/id/1147751232/photo/auto-parts-spare-parts-car-on-the-grey-background.jpg?s=612x612&w=0&k=20&c=8gE65zWyEu_l7G5XbiC3NmCCj_XaoHleJa86wfVu1NQ=",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 16,
      "sku": "ABC12345",
      "name": "Тормозной диск для Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для Honda Civic 2021 года",
      "description": "Этот высококачественный тормозной диск идеально подходит для модели Honda Civic 2021 года, обеспечивая превосходное торможение и долговечность даже в самых сложных эксплуатационных условиях.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1OvsdkJk5f7Co1T3Nr4a7ttWRIW9TKi3mgQ&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 17,
      "sku": "ABK12345",
      "name": "Тормозной диск для Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для Honda Civic 2021 года",
      "description": "Этот высококачественный тормозной диск идеально подходит для модели Honda Civic 2021 года, обеспечивая превосходное торможение и долговечность даже в самых сложных эксплуатационных условиях.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRG4F4XOCTjvQjXOqipC8UvI3j9-VyQovFgA&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 18,
      "sku": "KIJY7847",
      "name": "Тормозной диск для Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для Honda Civic 2021 года",
      "description": "Этот высококачественный тормозной диск идеально подходит для модели Honda Civic 2021 года, обеспечивая превосходное торможение и долговечность даже в самых сложных эксплуатационных условиях.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://st2.depositphotos.com/6644020/11546/i/450/depositphotos_115468952-stock-photo-industrial-spare-parts.jpg",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 19,
      "sku": "UYH38475",
      "name": "Тормозной диск для Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для Honda Civic 2021 года",
      "description": "Этот высококачественный тормозной диск идеально подходит для модели Honda Civic 2021 года, обеспечивая превосходное торможение и долговечность даже в самых сложных эксплуатационных условиях.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHyvg1JEk8bgaOl-gquatM5FZv4BVkXAncxA&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  },
  {
      "id": 20,
      "sku": "HGT38475",
      "name": "Тормозной диск для Honda",
      "visibilityInCatalog": "видимый",
      "language": "ru",
      "translationGroup": 2,
      "shortDescription": "Тормозной диск для Honda Civic 2021 года",
      "description": "Этот высококачественный тормозной диск идеально подходит для модели Honda Civic 2021 года, обеспечивая превосходное торможение и долговечность даже в самых сложных эксплуатационных условиях.",
      "inStock": true,
      "images": [],
      "carName": "Honda Civic",
      "model": "2021",
      "oem": "OEM9876",
      "years": "2016-2021",
      "price": 150,
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHyvg1JEk8bgaOl-gquatM5FZv4BVkXAncxA&s",
      "trtCode": "7654321",
      "brand": "Honda",
      "categories": []
  }
]